### ISSUE TITLE
Have you been trained the model on some pedestrian dataset?

### ISSUE THREAD

**Issue by holyhao** [sahibdhanjal/Mask-RCNN-Pedestrian-Detection#1]
For pedestrian detection, there are some datasets. Can we get better results by fine-tuning the model on them?

**Comment by sahibdhanjal** [comment]
We've used per-trained weights for the Mask RCNN here, which itself is very efficient in detecting people. While testing, we couldn't find any case where pedestrians visible to the human eye weren't detected in the video feed, hence I don't think fine-tuning based on pedestrian datasets would help our case. However, if you find any such case, please do let me know and I'll look into it. Hope this answers your question.
