### ISSUE TITLE
About output of main.py

### ISSUE THREAD

**Issue by NainaSaid** [sahibdhanjal/Mask-RCNN-Pedestrian-Detection#2]
Hi. I ran the main.py module and this is the output that i am getting. 

Can you please tell me what does indicate? or please tell me which module will show a demo of pedestrian detection from a video?

Waiting for your response.

Thanks in advance.
![57343428_2613804942023651_426246478739013632_n](https://user-images.githubusercontent.com/40417893/56584258-dadf3e80-65f4-11e9-9c06-175b6e8e550e.jpg)

**Comment by sahibdhanjal** [comment]
Hi , the output that you see is the output when you run Mask RCNN. Depending on whether you have a GPU or not, it may take sometime to run the demo. ```main.py``` is the correct file to run and the given code runs the test on the video ```test/Pedestrian overpass.mp4``` . You can change this on line 88. Let me know if you're able to see anything after running the whole thing. 
I would also suggest using an anaconda environment and running it from the terminal if you're running it on Windows.

**Comment by NainaSaid** [comment]
Thanks alot. i will report once i have run the whole thing :)

**Comment by NainaSaid** [comment]
Hi, so i ran the main.py file and after sometime i got this error. Can you please tell why am i getting this error?
![58654710_711630675958183_5663893048203935744_n](https://user-images.githubusercontent.com/40417893/57057543-e69cc600-6cc2-11e9-8d52-97a030c392fb.png)
