### ISSUE TITLE
detecting only 'person' and 'bg' mask rcnn

### ISSUE THREAD

**Issue by sv176** [sahibdhanjal/Mask-RCNN-Pedestrian-Detection#4]
Hi sahibdhanjal,

Is it possible if you could point out in your code how you filtered the algorithm to only detect people and bg?

sv176

**Comment by sahibdhanjal** [comment]
Hi @sv176 
Sorry for the late reply. You can see the modification in the Mask RCNN visualizer here. class ID - 1 is designated for pedestrians

https://github.com/sahibdhanjal/Mask-RCNN-Pedestrian-Detection/blob/25971a30905f30d54e51f941d55a2083716b09d8/visualize.py#L112
